@base_url = http://localhost:5207

### Register a new user
POST {{base_url}}/register
Content-Type: application/json
Accept: application/json

{
    "Username": "testuser",
    "Password": "testpassword",
    "Role": "User"
}

###

### Login with the registered user
POST {{base_url}}/login
Content-Type: application/json
Accept: application/json

{
    "Username": "testuser",
    "Password": "testpassword"
}